### ISSUE TITLE
Curl-Error: Operation timed out after 1000 milliseconds with 0 bytes received $ERP_BASE_URL in "inc/conf.php" richtig gesetzt??

### ISSUE THREAD

**Issue by mxgross** [kivitendo/kivitendo-crm#7]
Hello,

after the installation we receive the follwing error when we access any of the CRM menu entries from the kivitendo menu.
`Curl-Error: Operation timed out after 1000 milliseconds with 0 bytes received
$ERP_BASE_URL in "inc/conf.php" richtig gesetzt??`

We tried several variants of our kvitiendos URLs in $ERP_BASE_URL without a change.
Our kivitendo-erp folder is in /opt directory and apache is configured so that it leads directly into /opt/kivitendo-erp/

We access the ERP with "http://our-IP/" and Kivitendo routs us to "http://our-IP/kivitendo-erp".
A CRM URL looks e.g. like the following: http://our-IP/kivitendo-erp/crm/defaults.phtml

As ERP_BASE_URL we tried our-IP, our-IP/kivitendo-erp, kivitendo-erp, /, ... without any change.

Has anyone an idea what is still wrong?
Thanks

**Comment by Ciatronical** [comment]
please try the following installation script:
https://github.com/Ciatronical/install-kivitendo
